# Generated by Django 2.2.6 on 2019-11-03 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=750)),
                ('author', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('date_published', models.DateTimeField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('BR', 'Breaking News'), ('Response', 'Response'), ('JK', 'Just kidding'), ('MT', 'My Thoughts'), ('NH', 'Need Help')], max_length=2)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['author', 'title', '-type', 'text'],
            },
        ),
    ]
